data = [
    {
        "person": "Cristiano Ronaldo",
        "followers": 655,
        "country": "Portugal",
        "occupation": "Footballer",
    },
    {
        "person": "Lionel Messi",
        "followers": 505,
        "country": "Argentina",
        "occupation": "Footballer",
    },
    {
        "person": "Selena Gomez",
        "followers": 418,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Kylie Jenner",
        "followers": 393,
        "country": "USA",
        "occupation": "Businesswoman",
    },
    {
        "person": "Dwayne Johnson",
        "followers": 394,
        "country": "USA",
        "occupation": "Actor",
    },
    {
        "person": "Ariana Grande",
        "followers": 375,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Kim Kardashian",
        "followers": 357,
        "country": "USA",
        "occupation": "TV Personality",
    },
    {
        "person": "Beyonce",
        "followers": 313,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Khloe Kardashian",
        "followers": 303,
        "country": "USA",
        "occupation": "TV Personality",
    },
    {
        "person": "Nike",
        "followers": 305,
        "country": "USA",
        "occupation": "Brand",
    },
    {
        "person": "Justin Bieber",
        "followers": 294,
        "country": "Canada",
        "occupation": "Singer",
    },
    {
        "person": "Kendall Jenner",
        "followers": 287,
        "country": "USA",
        "occupation": "Model",
    },
    {
        "person": "Taylor Swift",
        "followers": 282,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Virat Kohli",
        "followers": 273,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "Jennifer Lopez",
        "followers": 248,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Neymar Jr",
        "followers": 230,
        "country": "Brazil",
        "occupation": "Footballer",
    },
    {
        "person": "Nicki Minaj",
        "followers": 226,
        "country": "USA",
        "occupation": "Rapper",
    },
    {
        "person": "Kourtney Kardashian",
        "followers": 220,
        "country": "USA",
        "occupation": "TV Personality",
    },
    {
        "person": "Miley Cyrus",
        "followers": 214,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Katy Perry",
        "followers": 205,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Zendaya",
        "followers": 183,
        "country": "USA",
        "occupation": "Actress",
    },
    {
        "person": "Kevin Hart",
        "followers": 177,
        "country": "USA",
        "occupation": "Comedian",
    },
    {
        "person": "Cardi B",
        "followers": 164,
        "country": "USA",
        "occupation": "Rapper",
    },
    {
        "person": "LeBron James",
        "followers": 160,
        "country": "USA",
        "occupation": "Basketball Player",
    },
    {
        "person": "Shakira",
        "followers": 153,
        "country": "Colombia",
        "occupation": "Singer",
    },
    {
        "person": "Demi Lovato",
        "followers": 153,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Chris Brown",
        "followers": 144,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Billie Eilish",
        "followers": 124,
        "country": "USA",
        "occupation": "Singer",
    },
    {
        "person": "Shraddha Kapoor",
        "followers": 95,
        "country": "India",
        "occupation": "Actress",
    },
    {
        "person": "Priyanka Chopra",
        "followers": 92,
        "country": "India",
        "occupation": "Actress",
    },
    {
        "person": "Narendra Modi",
        "followers": 92,
        "country": "India",
        "occupation": "Prime Minister",
    },
    {
        "person": "Deepika Padukone",
        "followers": 80,
        "country": "India",
        "occupation": "Actress",
    },
    {
        "person": "Alia Bhatt",
        "followers": 87,
        "country": "India",
        "occupation": "Actress",
    },
    {
        "person": "Akshay Kumar",
        "followers": 67,
        "country": "India",
        "occupation": "Actor",
    },
    {
        "person": "Salman Khan",
        "followers": 70,
        "country": "India",
        "occupation": "Actor",
    },
    {
        "person": "MS Dhoni",
        "followers": 50,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "Rohit Sharma",
        "followers": 43,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "Hardik Pandya",
        "followers": 38,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "KL Rahul",
        "followers": 22,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "Jasprit Bumrah",
        "followers": 21,
        "country": "India",
        "occupation": "Cricketer",
    },
    {
        "person": "Elon Musk",
        "followers": 7,
        "country": "USA",
        "occupation": "Entrepreneur",
    },
    {
        "person": "Mark Zuckerberg",
        "followers": 15,
        "country": "USA",
        "occupation": "Entrepreneur",
    },
    {
        "person": "MrBeast",
        "followers": 72,
        "country": "USA",
        "occupation": "YouTuber",
    },
    {
        "person": "Emma Watson",
        "followers": 74,
        "country": "United Kingdom",
        "occupation": "Actress",
    },
    {
        "person": "Tom Holland",
        "followers": 67,
        "country": "United Kingdom",
        "occupation": "Actor",
    },
    {
        "person": "Zac Efron",
        "followers": 61,
        "country": "USA",
        "occupation": "Actor",
    },
    {
        "person": "Gal Gadot",
        "followers": 109,
        "country": "Israel",
        "occupation": "Actress",
    },
    {
        "person": "Chris Hemsworth",
        "followers": 59,
        "country": "Australia",
        "occupation": "Actor",
    },
    {
        "person": "Robert Downey Jr.",
        "followers": 58,
        "country": "USA",
        "occupation": "Actor",
    },
    {
        "person": "Will Smith",
        "followers": 70,
        "country": "USA",
        "occupation": "Actor",
    },
]
